spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:usersdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never   # evita procurar schema.sql/data.sql no test
  h2:
    console:
      enabled: true
      path: /h2

  flyway:
    enabled: false

logging:
  level:
    root: warn

management:
  endpoints:
    web:
      exposure:
        include: health, info, env
  endpoint:
    health:
      show-details: always
    env:
      show-values: always   # when_authorized/never

